import {SchemaMap} from '../types/schema';

export const schemaMaps: SchemaMap[] = [
	{
		version: {min: 0, max: Infinity},
		map: [
			{
				table: ['CURRTYPE', 'currencyTypes'],
				columns: [
					['curr_id', 'currId', 'NUMBER'],
					['decimal_digit_cnt', 'decimalDigitCnt', 'NUMBER'],
					['curr_symbol', 'currSymbol', 'TEXT'],
					['decimal_symbol', 'decimalSymbol', 'TEXT'],
					['digit_group_symbol', 'digitGroupSymbol', 'TEXT'],
					['pos_curr_fmt_type', 'posCurrFmtType', 'TEXT'],
					['neg_curr_fmt_type', 'negCurrFmtType', 'TEXT'],
					['curr_type', 'currType', 'TEXT'],
					['curr_short_name', 'currShortName', 'TEXT'],
					['group_digit_cnt', 'groupDigitCnt', 'NUMBER'],
					['base_exch_rate', 'baseExchRate', 'NUMBER']
				]
			},
			{
				table: ['FINTMPL', 'financialTemplates'],
				columns: [
					['fintmpl_id', 'fintmplId', 'NUMBER'],
					['fintmpl_name', 'fintmplName', 'TEXT'],
					['default_flag', 'defaultFlag', 'TEXT']
				]
			},
			{
				table: ['MEMOTYPE', 'memoTypes'],
				columns: [
					['memo_type_id', 'memoTypeId', 'NUMBER'],
					['seq_num', 'seqNum', 'NUMBER'],
					['eps_flag', 'epsFlag', 'TEXT'],
					['proj_flag', 'projFlag', 'TEXT'],
					['wbs_flag', 'wbsFlag', 'TEXT'],
					['task_flag', 'taskFlag', 'TEXT'],
					['memo_type', 'memoType', 'TEXT']
				]
			},
			{
				table: ['OBS', 'obs'],
				columns: [
					['obs_id', 'obsId', 'NUMBER'],
					['parent_obs_id', 'parentObsId', 'NUMBER'],
					['guid', 'guid', 'TEXT'],
					['seq_num', 'seqNum', 'NUMBER'],
					['obs_name', 'obsName', 'TEXT'],
					['obs_descr', 'obsDescr', 'TEXT']
				]
			},
			{
				table: ['UDFTYPE', 'udfTypes'],
				columns: [
					['udf_type_id', 'udfTypeId', 'NUMBER'],
					['table_name', 'tableName', 'TEXT'],
					['udf_type_name', 'udfTypeName', 'TEXT'],
					['udf_type_label', 'udfTypeLabel', 'TEXT'],
					['logical_data_type', 'logicalDataType', 'TEXT'],
					['super_flag', 'superFlag', 'TEXT'],
					['indicator_expression', 'indicatorExpression', 'OTEXT'],
					['summary_indicator_expression', 'summaryIndicatorExpression', 'OTEXT'],
					['export_flag', 'exportFlag', 'TEXT']
				]
			},
			{
				table: ['ROLES', 'roles'],
				columns: [
					['role_id', 'roleId', 'NUMBER'],
					['parent_role_id', 'parentRoleId', 'ONUMBER'],
					['seq_num', 'seqNum', 'NUMBER'],
					['role_name', 'roleName', 'TEXT'],
					['role_short_name', 'roleShortName', 'TEXT'],
					['pobs_id', 'pobsId', 'ONUMBER'],
					['def_cost_qty_link_flag', 'defCostQtyLinkFlag', 'TEXT'],
					['cost_qty_type', 'costQtyType', 'TEXT'],
					['role_descr', 'roleDescr', 'OTEXT'],
					['last_checksum', 'lastChecksum', 'NUMBER']
				]
			},
			{
				table: ['PROJECT', 'projects'],
				columns: [
					['proj_id', 'projId', 'NUMBER'],
					['fy_start_month_num', 'fyStartMonthNum', 'NUMBER'],
					['rsrc_self_add_flag', 'rsrcSelfAddFlag', 'TEXT'],
					['allow_complete_flag', 'allowCompleteFlag', 'TEXT'],
					['rsrc_multi_assign_flag', 'rsrcMultiAssignFlag', 'TEXT'],
					['checkout_flag', 'checkoutFlag', 'TEXT'],
					['project_flag', 'projectFlag', 'TEXT'],
					['step_complete_flag', 'stepCompleteFlag', 'TEXT'],
					['cost_qty_recalc_flag', 'costQtyRecalcFlag', 'TEXT'],
					['batch_sum_flag', 'batchSumFlag', 'TEXT'],
					['name_sep_char', 'nameSepChar', 'NUMBER'],
					['def_complete_pct_type', 'defCompletePctType', 'TEXT'],
					['proj_short_name', 'projShortName', 'TEXT'],
					['acct_id', 'acctId', 'ONUMBER'],
					['orig_proj_id', 'origProjId', 'ONUMBER'],
					['source_proj_id', 'sourceProjId', 'ONUMBER'],
					['base_type_id', 'baseTypeId', 'ONUMBER'],
					['clndr_id', 'clndrId', 'NUMBER'],
					['sum_base_proj_id', 'sumBaseProjId', 'ONUMBER'],
					['task_code_base', 'taskCodeBase', 'TEXT'],
					['task_code_step', 'taskCodeStep', 'TEXT'],
					['priority_num', 'priorityNum', 'NUMBER'],
					['wbs_max_sum_level', 'wbsMaxSumLevel', 'NUMBER'],
					['strgy_priority_num', 'strgyPriorityNum', 'NUMBER'],
					['last_checksum', 'lastChecksum', 'ONUMBER'],
					['critical_drtn_hr_cnt', 'criticalDrtnHrCnt', 'NUMBER'],
					['def_cost_per_qty', 'defCostPerHr', 'NUMBER'],
					['last_recalc_date', 'lastRecalcDate', 'DATE'],
					['plan_start_date', 'planStartDate', 'DATE'],
					['plan_end_date', 'planEndDate', 'ODATE'],
					['scd_end_date', 'scdEndDate', 'ODATE'],
					['add_date', 'addDate', 'DATE'],
					['last_tasksum_date', 'lastTasksumDate', 'ODATE'],
					['fcst_start_date', 'fcstStartDate', 'ODATE'],
					['def_duration_type', 'defDurationType', 'TEXT'],
					['task_code_prefix', 'taskCodePrefix', 'TEXT'],
					['guid', 'guid', 'TEXT'],
					['def_qty_type', 'defQtyType', 'TEXT'],
					['add_by_name', 'addByName', 'TEXT'],
					['web_local_root_path', 'webLocalRootPath', 'OTEXT'],
					['proj_url', 'projUrl', 'OTEXT'],
					['def_rate_type', 'defRateType', 'TEXT'],
					['add_act_remain_flag', 'addActRemainFlag', 'TEXT'],
					['act_this_per_link_flag', 'actThisPerLinkFlag', 'TEXT'],
					['def_task_type', 'defTaskType', 'TEXT'],
					['act_pct_link_flag', 'actPctLinkFlag', 'TEXT'],
					['critical_path_type', 'criticalPathType', 'TEXT'],
					['task_code_prefix_flag', 'taskCodePrefixFlag', 'TEXT'],
					['def_rollup_dates_flag', 'defRollupDatesFlag', 'TEXT'],
					['use_project_baseline_flag', 'useProjectBaselineFlag', 'TEXT'],
					['rem_target_link_flag', 'remTargetLinkFlag', 'TEXT'],
					['reset_planned_flag', 'resetPlannedFlag', 'TEXT'],
					['allow_neg_act_flag', 'allowNegActFlag', 'TEXT'],
					['sum_assign_level', 'sumAssignLevel', 'TEXT'],
					['last_fin_dates_id', 'lastFinDatesId', 'ONUMBER'],
					['fintmpl_id', 'fintmplDd', 'NUMBER'],
					['last_baseline_update_date', 'lastBaselineUpdateDate', 'ODATE'],
					['cr_external_key', 'crExternalKey', 'OTEXT'],
					['apply_actuals_date', 'applyActualsDate', 'ODATE'],
					['location_id', 'locationId', 'ONUMBER'],
					['last_schedule_date', 'lastScheduleDate', 'ODATE'],
					['loaded_scope_level', 'loadedScopeLevel', 'TEXT'],
					['export_flag', 'exportFlag', 'TEXT'],
					['new_fin_dates_id', 'newFinDatesId', 'NUMBER'],
					['baselines_to_export', 'baselinesToExport', 'TEXT'],
					['baseline_names_to_export', 'baselineNamesToExport', 'TEXT'],
					['next_data_date', 'nextDataDate', 'DATE'],
					['close_period_flag', 'closePeriodFlag', 'TEXT'],
					['sum_refresh_date', 'sumRefreshDate', 'DATE'],
					['trsrcsum_loaded', 'trsrcsumLoaded', 'TEXT'],
					['sumtask_loaded', 'sumtaskLoaded', 'TEXT']
				]
			},
			{
				table: ['PHASE', 'phases'],
				columns: [
					['phase_id', 'phaseId', 'NUMBER'],
					['seq_num', 'seqNum', 'NUMBER'],
					['phase_name', 'phaseName', 'TEXT']
				]
			},
			{
				table: ['APPLYACTOPTIONS', 'applyActOptions'],
				columns: [
					['proj_id', 'projId', 'NUMBER'],
					['respect_duration_type', 'respectDurationType', 'TEXT']
				]
			},
			{
				table: ['DOCUMENT', 'documents'],
				columns: [
					['doc_id', 'docId', 'NUMBER'],
					['doc_seq_num', 'docSeqNum', 'NUMBER'],
					['deliv_flag', 'delivFlag', 'TEXT'],
					['doc_name', 'docName', 'TEXT'],
					['parent_doc_id', 'parentDocId', 'ONUMBER'],
					['proj_id', 'projId', 'NUMBER'],
					['doc_status_id', 'docStatusId', 'ONUMBER'],
					['doc_catg_id', 'docCatgId', 'ONUMBER'],
					['doc_date', 'docDate', 'ODATE'],
					['version_name', 'versionName', 'OTEXT'],
					['guid', 'guid', 'TEXT'],
					['tmpl_guid', 'tmplGuid', 'OTEXT'],
					['doc_short_name', 'docShortName', 'OTEXT'],
					['author_name', 'authorName', 'OTEXT'],
					['private_loc', 'privateLoc', 'OTEXT'],
					['public_loc', 'publicLoc', 'OTEXT'],
					['doc_mgmt_type', 'docMgmtType', 'TEXT'],
					['cr_external_doc_key', 'crExternalDocKey', 'OTEXT'],
					['doc_content', 'docContent', 'OTEXT']
				]
			},
			{
				table: ['ROLERATE', 'roleRates'],
				columns: [
					['role_rate_id', 'roleRateId', 'NUMBER'],
					['role_id', 'roleId', 'NUMBER'],
					['cost_per_qty', 'costPerQty', 'NUMBER'],
					['cost_per_qty2', 'costPerQty2', 'ONUMBER'],
					['cost_per_qty3', 'costPerQty3', 'ONUMBER'],
					['cost_per_qty4', 'costPerQty4', 'ONUMBER'],
					['cost_per_qty5', 'costPerQty5', 'ONUMBER'],
					['start_date', 'startDate', 'DATE'],
					['max_qty_per_hr', 'maxQtyPerHr', 'NUMBER']
				]
			},
			{
				table: ['CALENDAR', 'calendars'],
				columns: [
					['clndr_id', 'clndrId', 'NUMBER'],
					['default_flag', 'defaultFlag', 'TEXT'],
					['clndr_name', 'clndrName', 'TEXT'],
					['proj_id', 'projId', 'ONUMBER'],
					['base_clndr_id', 'baseClndrId', 'ONUMBER'],
					['last_chng_date', 'lastChngDate', 'ODATE'],
					['clndr_type', 'clndrType', 'TEXT'],
					['day_hr_cnt', 'dayHrCnt', 'NUMBER'],
					['week_hr_cnt', 'weekHrCnt', 'NUMBER'],
					['month_hr_cnt', 'monthHrCnt', 'NUMBER'],
					['year_hr_cnt', 'yearHrCnt', 'NUMBER'],
					['rsrc_private', 'rsrcPrivate', 'TEXT'],
					['clndr_data', 'clndrData', 'TEXT']
				]
			},
			{
				table: ['SCHEDOPTIONS', 'scheduleOptions'],
				columns: [
					['schedoptions_id', 'schedoptionsId', 'NUMBER'],
					['proj_id', 'projId', 'NUMBER'],
					['sched_outer_depend_type', 'schedOuterDependType', 'TEXT'],
					['sched_open_critical_flag', 'schedOpenCriticalFlag', 'TEXT'],
					['sched_lag_early_start_flag', 'schedLagEarlyStartFlag', 'TEXT'],
					['sched_retained_logic', 'schedRetainedLogic', 'TEXT'],
					['sched_setplantoforecast', 'schedSetplantoforecast', 'TEXT'],
					['sched_float_type', 'schedFloatType', 'TEXT'],
					['sched_calendar_on_relationship_lag', 'schedCalendarOnRelationshipLag', 'NUMBER'],
					['sched_use_expect_end_flag', 'schedUseExpectEndFlag', 'TEXT'],
					['sched_progress_override', 'schedProgressOverride', 'TEXT'],
					['level_float_thrs_cnt', 'levelFloatThrsCnt', 'NUMBER'],
					['level_outer_assign_flag', 'levelOuterAssignFlag', 'TEXT'],
					['level_outer_assign_priority', 'levelOuterAssignPriority', 'TEXT'],
					['level_over_alloc_pct', 'levelOverAllocPct', 'NUMBER'],
					['level_within_float_flag', 'levelWithinFloatFlag', 'TEXT'],
					['level_keep_sched_date_flag', 'levelKeepSchedDateFlag', 'TEXT'],
					['level_all_rsrc_flag', 'levelAllRsrcFlag', 'TEXT'],
					['sched_use_project_end_date_for_float', 'schedUseProjectEndDateForFloat', 'TEXT'],
					['enable_multiple_longest_path_calc', 'enableMultipleLongestPathCalc', 'TEXT'],
					['limit_multiple_longest_path_calc', 'limitMultipleLongestPathCalc', 'TEXT'],
					['max_multiple_longest_path', 'maxMultipleLongestPath', 'NUMBER'],
					['use_total_float_multiple_longest_paths', 'useTotalFloatMultipleLongestPaths', 'TEXT'],
					['key_activity_for_multiple_longest_paths', 'keyActivityForMultipleLongestPaths', 'TEXT'],
					['LevelPriorityList', 'LevelPriorityList', 'TEXT']
				]
			},
			{
				table: ['PROJWBS', 'projWBS'],
				columns: [
					['wbs_id', 'wbsId', 'NUMBER'],
					['proj_id', 'projId', 'NUMBER'],
					['obs_id', 'obsId', 'NUMBER'],
					['seq_num', 'seqNum', 'NUMBER'],
					['est_wt', 'estWt', 'NUMBER'],
					['proj_node_flag', 'projNodeFlag', 'TEXT'],
					['sum_data_flag', 'sumDataFlag', 'TEXT'],
					['status_code', 'statusCode', 'TEXT'],
					['wbs_short_name', 'wbsShortName', 'TEXT'],
					['wbs_name', 'wbsName', 'TEXT'],
					['phase_id', 'phaseId', 'ONUMBER'],
					['parent_wbs_id', 'parentWbsId', 'ONUMBER'],
					['ev_user_pct', 'evUserPct', 'NUMBER'],
					['ev_etc_user_value', 'evEtcUserValue', 'NUMBER'],
					['orig_cost', 'origCost', 'ONUMBER'],
					['indep_remain_total_cost', 'indepRemainTotalCost', 'ONUMBER'],
					['ann_dscnt_rate_pct', 'annDscntRatePct', 'ONUMBER'],
					['dscnt_period_type', 'dscntPeriodType', 'TEXT'],
					['indep_remain_work_qty', 'indepRemainWorkQty', 'ONUMBER'],
					['anticip_start_date', 'anticipStartDate', 'ODATE'],
					['anticip_end_date', 'anticipEndDate', 'ODATE'],
					['ev_compute_type', 'evComputeType', 'TEXT'],
					['ev_etc_compute_type', 'evEtcComputeType', 'TEXT'],
					['guid', 'guid', 'TEXT'],
					['tmpl_guid', 'tmplGuid', 'OTEXT'],
					['plan_open_state', 'planOpenState', 'TEXT']
				]
			},
			{
				table: ['RSRC', 'resources'],
				columns: [
					['rsrc_id', 'rsrcId', 'NUMBER'],
					['parent_rsrc_id', 'parentRsrcId', 'ONUMBER'],
					['clndr_id', 'clndrId', 'NUMBER'],
					['role_id', 'roleId', 'ONUMBER'],
					['shift_id', 'shiftId', 'ONUMBER'],
					['user_id', 'userId', 'ONUMBER'],
					['pobs_id', 'pobsId', 'ONUMBER'],
					['guid', 'guid', 'TEXT'],
					['rsrc_seq_num', 'rsrcSeqNum', 'NUMBER'],
					['email_addr', 'emailAddr', 'OTEXT'],
					['employee_code', 'employeeCode', 'OTEXT'],
					['office_phone', 'officePhone', 'OTEXT'],
					['other_phone', 'otherPhone', 'OTEXT'],
					['rsrc_name', 'rsrcName', 'TEXT'],
					['rsrc_short_name', 'rsrcShortName', 'TEXT'],
					['rsrc_title_name', 'rsrcTitleName', 'OTEXT'],
					['def_qty_per_hr', 'defQtyPerHr', 'NUMBER'],
					['cost_qty_type', 'costQtyType', 'TEXT'],
					['ot_factor', 'otFactor', 'ONUMBER'],
					['active_flag', 'activeFlag', 'TEXT'],
					['auto_compute_act_flag', 'autoComputeActFlag', 'TEXT'],
					['def_cost_qty_link_flag', 'defCostQtyLinkFlag', 'TEXT'],
					['ot_flag', 'otFlag', 'TEXT'],
					['curr_id', 'currId', 'NUMBER'],
					['unit_id', 'unitId', 'ONUMBER'],
					['rsrc_type', 'rsrcType', 'TEXT'],
					['location_id', 'locationId', 'ONUMBER'],
					['rsrc_notes', 'rsrcNotes', 'OTEXT'],
					['load_tasks_flag', 'loadTasksFlag', 'TEXT'],
					['level_flag', 'levelFlag', 'TEXT'],
					['last_checksum', 'lastChecksum', 'ONUMBER']
				]
			},
			{
				table: ['ACTVTYPE', 'activityCodeTypes'],
				columns: [
					['actv_code_type_id', 'actvCodeTypeId', 'NUMBER'],
					['actv_short_len', 'actvShortLen', 'NUMBER'],
					['seq_num', 'seqNum', 'NUMBER'],
					['actv_code_type', 'actvCodeType', 'TEXT'],
					['proj_id', 'projId', 'ONUMBER'],
					['wbs_id', 'wbsId', 'NUMBER'],
					['actv_code_type_scope', 'actvCodeTypeScope', 'TEXT'],
					['export_flag', 'exportFlag', 'TEXT']
				]
			},
			{
				table: ['RSRCLEVELLIST', 'resourceLevelLists'],
				columns: [
					['rsrc_level_list_id', 'rsrcLevelListId', 'NUMBER'],
					['schedoptions_id', 'schedoptionsId', 'NUMBER'],
					['rsrc_id', 'rsrcId', 'NUMBER']
				]
			},
			{
				table: ['RSRCRATE', 'resourceRates'],
				columns: [
					['rsrc_rate_id', 'rsrcRateId', 'NUMBER'],
					['rsrc_id', 'rsrcId', 'NUMBER'],
					['max_qty_per_hr', 'maxQtyPerHr', 'NUMBER'],
					['cost_per_qty', 'costPerQty', 'NUMBER'],
					['start_date', 'startDate', 'DATE'],
					['shift_period_id', 'shiftPeriodId', 'ONUMBER'],
					['cost_per_qty2', 'costPerQty2', 'ONUMBER'],
					['cost_per_qty3', 'costPerQty3', 'ONUMBER'],
					['cost_per_qty4', 'costPerQty4', 'ONUMBER'],
					['cost_per_qty5', 'costPerQty5', 'ONUMBER']
				]
			},
			{
				table: ['RSRCROLE', 'resourceRoles'],
				columns: [
					['rsrc_id', 'rsrcId', 'NUMBER'],
					['role_id', 'roleId', 'NUMBER'],
					['skill_level', 'skillLevel', 'NUMBER'],
					['role_short_name', 'roleShortName', 'TEXT'],
					['role_name', 'roleName', 'TEXT'],
					['rsrc_short_name', 'rsrcShortName', 'TEXT'],
					['rsrc_name', 'rsrcName', 'TEXT'],
					['rsrc_type', 'rsrcType', 'TEXT'],
					['rsrc_role_id', 'rsrcRoleId', 'NUMBER']
				]
			},
			{
				table: ['TASK', 'tasks'],
				columns: [
					['task_id', 'taskId', 'NUMBER'],
					['proj_id', 'projId', 'NUMBER'],
					['wbs_id', 'wbsId', 'NUMBER'],
					['clndr_id', 'clndrId', 'NUMBER'],
					['phys_complete_pct', 'physCompletePct', 'NUMBER'],
					['rev_fdbk_flag', 'revFdbk', 'TEXT'],
					['est_wt', 'estWt', 'NUMBER'],
					['lock_plan_flag', 'lockPlan', 'TEXT'],
					['auto_compute_act_flag', 'autoComputeAct', 'TEXT'],
					['complete_pct_type', 'completePctType', 'TEXT'],
					['task_type', 'taskType', 'TEXT'],
					['duration_type', 'durationType', 'TEXT'],
					['status_code', 'statusCode', 'TEXT'],
					['task_code', 'taskCode', 'TEXT'],
					['task_name', 'taskName', 'TEXT'],
					['rsrc_id', 'rsrcId', 'ONUMBER'],
					['total_float_hr_cnt', 'totalFloat', 'NUMBER'],
					['free_float_hr_cnt', 'freeFloat', 'NUMBER'],
					['remain_drtn_hr_cnt', 'remainDrtn', 'NUMBER'],
					['act_work_qty', 'actWorkQty', 'NUMBER'],
					['remain_work_qty', 'remainWorkQty', 'NUMBER'],
					['target_work_qty', 'targetWorkQty', 'NUMBER'],
					['target_drtn_hr_cnt', 'targetDrtn', 'NUMBER'],
					['target_equip_qty', 'targetEquipQty', 'NUMBER'],
					['act_equip_qty', 'actEquipQty', 'NUMBER'],
					['remain_equip_qty', 'remainEquipQty', 'NUMBER'],
					['cstr_date', 'cstrDate', 'ODATE'],
					['act_start_date', 'actStartDate', 'ODATE'],
					['act_end_date', 'actEndDate', 'ODATE'],
					['late_start_date', 'lateStartDate', 'DATE'],
					['late_end_date', 'lateEndDate', 'DATE'],
					['expect_end_date', 'expectEndDate', 'ODATE'],
					['early_start_date', 'earlyStartDate', 'DATE'],
					['early_end_date', 'earlyEndDate', 'DATE'],
					['restart_date', 'restartDate', 'DATE'],
					['reend_date', 'reendDate', 'DATE'],
					['target_start_date', 'targetStartDate', 'DATE'],
					['target_end_date', 'targetEndDate', 'DATE'],
					['rem_late_start_date', 'remLateStartDate', 'DATE'],
					['rem_late_end_date', 'remLateEndDate', 'DATE'],
					['cstr_type', 'cstrType', 'OTEXT'],
					['priority_type', 'priorityType', 'TEXT'],
					['suspend_date', 'suspendDate', 'ODATE'],
					['resume_date', 'resumeDate', 'ODATE'],
					['float_path', 'floatPath', 'ONUMBER'],
					['float_path_order', 'floatPathOrder', 'ONUMBER'],
					['guid', 'guid', 'TEXT'],
					['tmpl_guid', 'tmplGuid', 'OTEXT'],
					['cstr_date2', 'cstrDate2', 'ODATE'],
					['cstr_type2', 'cstrType2', 'OTEXT'],
					['driving_path_flag', 'drivingPath', 'TEXT'],
					['act_this_per_work_qty', 'actThisPerWorkQty', 'NUMBER'],
					['act_this_per_equip_qty', 'actThisPerEquipQty', 'NUMBER'],
					['external_early_start_date', 'externalEarlyStartDate', 'ODATE'],
					['external_late_end_date', 'externalLateEndDate', 'ODATE'],
					['create_date', 'createDate', 'DATE'],
					['update_date', 'updateDate', 'DATE'],
					['create_user', 'createUser', 'TEXT'],
					['update_user', 'updateUser', 'TEXT'],
					['location_id', 'locationId', 'ONUMBER'],
					['crt_path_num', 'crtPathNum', 'ONUMBER']
				]
			},
			{
				table: ['ACTVCODE', 'activityCodes'],
				columns: [
					['actv_code_id', 'actvCodeId', 'NUMBER'],
					['parent_actv_code_id', 'parentActvCodeId', 'ONUMBER'],
					['actv_code_type_id', 'actvCodeTypeId', 'NUMBER'],
					['actv_code_name', 'actvCodeName', 'TEXT'],
					['short_name', 'shortName', 'TEXT'],
					['seq_num', 'seqNum', 'NUMBER'],
					['color', 'color', 'NUMBER'],
					['total_assignments', 'totalAssignments', 'NUMBER']
				]
			},
			{
				table: ['TASKMEMO', 'taskMemos'],
				columns: [
					['memo_id', 'memoId', 'NUMBER'],
					['task_id', 'taskId', 'NUMBER'],
					['memo_type_id', 'memoTypeId', 'NUMBER'],
					['proj_id', 'projId', 'NUMBER'],
					['task_memo', 'taskMemo', 'TEXT']
				]
			},
			{
				table: ['TASKPRED', 'taskPredecessors'],
				columns: [
					['task_pred_id', 'taskPredId', 'NUMBER'],
					['task_id', 'taskId', 'NUMBER'],
					['pred_task_id', 'predTaskId', 'NUMBER'],
					['proj_id', 'projId', 'NUMBER'],
					['pred_proj_id', 'predProjId', 'NUMBER'],
					['pred_type', 'predType', 'TEXT'],
					['lag_hr_cnt', 'lag', 'NUMBER'],
					['comments', 'comments', 'OTEXT'],
					['float_path', 'floatPath', 'TEXT'],
					['aref', 'aref', 'TEXT'],
					['arls', 'arls', 'TEXT']
				]
			},
			{
				table: ['TASKRSRC', 'taskResources'],
				columns: [
					['taskrsrc_id', 'taskrsrcId', 'NUMBER'],
					['task_id', 'taskId', 'NUMBER'],
					['proj_id', 'projId', 'NUMBER'],
					['cost_qty_link_flag', 'costQtyLinkFlag', 'TEXT'],
					['role_id', 'roleId', 'NUMBER'],
					['acct_id', 'acctId', 'ONUMBER'],
					['rsrc_id', 'rsrcId', 'NUMBER'],
					['pobs_id', 'pobsId', 'ONUMBER'],
					['skill_level', 'skillLevel', 'NUMBER'],
					['remain_qty', 'remainQty', 'NUMBER'],
					['target_qty', 'targetQty', 'NUMBER'],
					['remain_qty_per_hr', 'remainQtyPerHr', 'NUMBER'],
					['target_lag_drtn_hr_cnt', 'targetLag', 'NUMBER'],
					['target_qty_per_hr', 'targetQtyPerHr', 'NUMBER'],
					['act_ot_qty', 'actOtQty', 'NUMBER'],
					['act_reg_qty', 'actRegQty', 'NUMBER'],
					['relag_drtn_hr_cnt', 'relag', 'NUMBER'],
					['ot_factor', 'otFactor', 'ONUMBER'],
					['cost_per_qty', 'costPerQty', 'NUMBER'],
					['target_cost', 'targetCost', 'NUMBER'],
					['act_reg_cost', 'actRegCost', 'NUMBER'],
					['act_ot_cost', 'actOtCost', 'NUMBER'],
					['remain_cost', 'remainCost', 'NUMBER'],
					['act_start_date', 'actStartDate', 'ODATE'],
					['act_end_date', 'actEndDate', 'ODATE'],
					['restart_date', 'restartDate', 'DATE'],
					['reend_date', 'reendDate', 'DATE'],
					['target_start_date', 'targetStartDate', 'DATE'],
					['target_end_date', 'targetEndDate', 'DATE'],
					['rem_late_start_date', 'remLateStartDate', 'DATE'],
					['rem_late_end_date', 'remLateEndDate', 'DATE'],
					['rollup_dates_flag', 'rollupDatesFlag', 'TEXT'],
					['target_crv', 'targetCrv', 'ONUMBER'],
					['remain_crv', 'remainCrv', 'ONUMBER'],
					['actual_crv', 'actualCrv', 'ONUMBER'],
					['ts_pend_act_end_flag', 'tsPendActEndFlag', 'TEXT'],
					['guid', 'guid', 'TEXT'],
					['rate_type', 'rateType', 'TEXT'],
					['act_this_per_cost', 'actThisPerCost', 'NUMBER'],
					['act_this_per_qty', 'actThisPerQty', 'NUMBER'],
					['curv_id', 'curvId', 'ONUMBER'],
					['rsrc_type', 'rsrcType', 'TEXT'],
					['cost_per_qty_source_type', 'costPerQtySourceType', 'TEXT'],
					['create_user', 'createUser', 'TEXT'],
					['create_date', 'createDate', 'DATE'],
					['has_rsrchours', 'hasRsrchours', 'TEXT'],
					['taskrsrc_sum_id', 'taskrsrcSumId', 'NUMBER']
				]
			},
			{
				table: ['TASKACTV', 'taskActivityCodes'],
				columns: [
					['task_id', 'taskId', 'NUMBER'],
					['actv_code_type_id', 'actvCodeTypeId', 'NUMBER'],
					['actv_code_id', 'actvCodeId', 'NUMBER'],
					['proj_id', 'projId', 'NUMBER']
				]
			},
			{
				table: ['UDFVALUE', 'udfValues'],
				columns: [
					['udf_type_id', 'udfTypeId', 'NUMBER'],
					['fk_id', 'fkId', 'NUMBER'],
					['proj_id', 'projId', 'NUMBER'],
					['udf_date', 'udfDate', 'ODATE'],
					['udf_number', 'udfNumber', 'ONUMBER'],
					['udf_text', 'udfText', 'OTEXT'],
					['udf_code_id', 'udfCodeId', 'ONUMBER']
				]
			}
			// ['CURRTYPE', 'currencyTypes'],
			// ['FINTMPL', 'financialTemplates'],
			// ['MEMOTYPE', 'memoTypes'],
			// ['OBS', 'obs'],
			// ['UDFTYPE', 'udfTypes'],
			// ['ROLES', 'roles'],
			// ['PROJECT', 'projects'],
			// ['ROLERATE', 'roleRates'],
			// ['CALENDAR', 'calendars'],
			// ['SCHEDOPTIONS', 'scheduleOptions'],
			// ['PROJWBS', 'projWBS'],
			// ['RSRC', 'resources'],
			// ['ACTVTYPE', 'activityCodeTypes'],
			// ['RSRCLEVELLIST', 'resourceLevelLists'],
			// ['RSRCRATE', 'resourceRates'],
			// ['RSRCROLE', 'resourceRoles'],
			// ['TASK', 'tasks'],
			// ['ACTVCODE', 'activityCodes'],
			// ['TASKMEMO', 'taskMemos'],
			// ['TASKPRED', 'taskPredecessors'],
			// ['TASKRSRC', 'taskResources'],
			// ['TASKACTV', 'taskActivityCodes'],
			// ['UDFVALUE', 'udfValues']
		]
	}
];
